# Generated by Django 4.0.4 on 2022-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('phoneno', models.CharField(blank=True, max_length=500)),
                ('symptoms', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(default='[]', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('surname', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('phoneno', models.CharField(blank=True, max_length=500)),
                ('district', models.CharField(blank=True, max_length=500)),
                ('pincode', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, max_length=500)),
                ('adhaarno', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
